name: Deploy Documentation

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' #
      - name: Install dependencies
        run: npm install 
      # Générer la documentation
      - name: Generate Documentation
        run: npm run docs 
